services:
  - type: web
    name: product-importer-api
    env: docker
    repo: https://github.com/ayushi-gajendra/Product-Importer.git
    plan: free
    autoDeploy: true
    dockerCommand: flask run --host=0.0.0.0 --port=8000
    ipAllowList:
      - 0.0.0.0/0
    envVars:
      - key: FLASK_APP
        value: app.main
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: product-importer-kv
          property: connectionString

  - type: worker
    name: product-importer-worker
    env: docker
    repo: https://github.com/ayushi-gajendra/Product-Importer.git
    plan: free
    autoDeploy: true
    dockerCommand: celery -A app.tasks worker --loglevel=info
    ipAllowList:
      - 0.0.0.0/0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: product-importer-kv
          property: connectionString

  - type: keyvalue
    name: product-importer-kv
    plan: free

databases:
  - name: product-importer-db
    plan: free
